# Render deployment configuration
services:
  - type: web
    name: the-digital-cart-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false  # Set this manually in Render dashboard
      - key: JWT_SECRET
        sync: false  # Set this manually in Render dashboard
      - key: CLOUDINARY_CLOUD_NAME
        sync: false  # Set this manually in Render dashboard
      - key: CLOUDINARY_API_KEY
        sync: false  # Set this manually in Render dashboard
      - key: CLOUDINARY_API_SECRET
        sync: false  # Set this manually in Render dashboard
      - key: CORS_ORIGIN
        sync: false  # Set this manually in Render dashboard